# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raytracerGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtGui import QPixmap, QIcon, QFont
import app


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Image container
        self.image_container = QtWidgets.QGraphicsView(self.centralwidget)
        self.image_container.setGeometry(QtCore.QRect(600, 10, 1200, 800))
        self.image_container.setObjectName("image_container")

        # Progress Bar
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(600, 823, 500, 50))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        # Scene Group Box
        self.scene_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.scene_groupBox.setGeometry(QtCore.QRect(80, 700, 400, 100))
        self.scene_groupBox.setObjectName("scene_groupBox")
        self.scene_groupBox.setStyleSheet(
            "font-weight: bold; border: 4px solid black;")

        self.load_btn = QtWidgets.QPushButton(self.scene_groupBox)
        self.load_btn.setGeometry(QtCore.QRect(10, 40, 93, 28))
        self.load_btn.setObjectName("load_btn")
        self.load_btn.clicked.connect(self.load_image)

        # Start raytracer Button
        self.start_btn = QtWidgets.QPushButton(self.scene_groupBox)
        self.start_btn.setGeometry(QtCore.QRect(130, 40, 93, 28))
        self.start_btn.setObjectName("start_btn")
        self.start_btn.hide()

        self.save_btn = QtWidgets.QPushButton(self.scene_groupBox)
        self.save_btn.setGeometry(QtCore.QRect(250, 40, 93, 28))
        self.save_btn.setObjectName("save_btn")
        self.save_btn.hide()

        # Camera Group Box
        self.camera_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.camera_groupBox.setGeometry(QtCore.QRect(80, 460, 171, 131))
        self.camera_groupBox.setObjectName("camera_groupBox")
        self.camera_groupBox.setStyleSheet(
            "font-weight: bold; border: 1px solid black;")

        self.distance_spinBox = QtWidgets.QSpinBox(self.camera_groupBox)
        self.distance_spinBox.setGeometry(QtCore.QRect(100, 40, 42, 22))
        self.distance_spinBox.setObjectName("distance_spinBox")
        self.distance_spinBox.setMaximum(5000)
        self.distance_label = QtWidgets.QLabel(self.camera_groupBox)
        self.distance_label.setGeometry(QtCore.QRect(20, 40, 55, 16))
        self.distance_label.setObjectName("distance_label")
        self.fov_label = QtWidgets.QLabel(self.camera_groupBox)
        self.fov_label.setGeometry(QtCore.QRect(10, 80, 81, 41))
        self.fov_label.setObjectName("fov_label")
        self.fov_spinBox = QtWidgets.QSpinBox(self.camera_groupBox)
        self.fov_spinBox.setGeometry(QtCore.QRect(100, 90, 42, 22))
        self.fov_spinBox.setObjectName("fov_spinBox")
        self.fov_spinBox.setMaximum(5000)

        # Image Group Box
        self.image_groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.image_groupBox_3.setGeometry(QtCore.QRect(300, 270, 181, 171))
        self.image_groupBox_3.setObjectName("image_groupBox_3")
        self.image_groupBox_3.setStyleSheet(
            "font-weight: bold; border: 1px solid black;")

        self.horizontal_spinBox_6 = QtWidgets.QSpinBox(self.image_groupBox_3)
        self.horizontal_spinBox_6.setGeometry(QtCore.QRect(90, 70, 42, 22))
        self.horizontal_spinBox_6.setObjectName("horizontal_spinBox_6")
        self.horizontal_spinBox_6.setMaximum(3840)
        self.horizontal_label_5 = QtWidgets.QLabel(self.image_groupBox_3)
        self.horizontal_label_5.setGeometry(QtCore.QRect(20, 70, 61, 16))
        self.horizontal_label_5.setObjectName("horizontal_label_5")
        self.resolution_label_4 = QtWidgets.QLabel(self.image_groupBox_3)
        self.resolution_label_4.setGeometry(QtCore.QRect(70, 40, 61, 16))
        self.resolution_label_4.setObjectName("resolution_label_4")
        self.vertical_label_6 = QtWidgets.QLabel(self.image_groupBox_3)
        self.vertical_label_6.setGeometry(QtCore.QRect(20, 110, 61, 16))
        self.vertical_label_6.setObjectName("vertical_label_6")
        self.vertical_spinBox_7 = QtWidgets.QSpinBox(self.image_groupBox_3)
        self.vertical_spinBox_7.setGeometry(QtCore.QRect(90, 110, 42, 22))
        self.vertical_spinBox_7.setObjectName("vertical_spinBox_7")
        self.vertical_spinBox_7.setMaximum(2160)

        # Renderer Group Box
        self.renderer_groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.renderer_groupBox_4.setGeometry(QtCore.QRect(80, 270, 181, 171))
        self.renderer_groupBox_4.setObjectName("renderer_groupBox_4")
        self.renderer_groupBox_4.setStyleSheet(
            "font-weight: bold; border: 1px solid black;")

        self.horizontal_spinBox_8 = QtWidgets.QSpinBox(
            self.renderer_groupBox_4)
        self.horizontal_spinBox_8.setGeometry(QtCore.QRect(120, 70, 42, 22))
        self.horizontal_spinBox_8.setObjectName("horizontal_spinBox_8")
        self.horizontal_spinBox_8.setMaximum(3840)
        self.recursion_label_7 = QtWidgets.QLabel(self.renderer_groupBox_4)
        self.recursion_label_7.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.recursion_label_7.setObjectName("recursion_label_7")
        self.start_btn_2 = QtWidgets.QPushButton(self.renderer_groupBox_4)
        self.start_btn_2.setGeometry(QtCore.QRect(20, 120, 93, 28))
        self.start_btn_2.setObjectName("start_btn_2")
        MainWindow.setCentralWidget(self.centralwidget)

        # Transformation Group Box
        self.transformation_groupBox_3 = QtWidgets.QGroupBox(
            self.centralwidget)
        self.transformation_groupBox_3.setGeometry(
            QtCore.QRect(80, 80, 291, 171))
        self.transformation_groupBox_3.setObjectName(
            "transformation_groupBox_3")
        self.transformation_groupBox_3.setStyleSheet(
            "font-weight: bold; border: 1px solid black;")

        self.x_spinBox_3 = QtWidgets.QSpinBox(self.transformation_groupBox_3)
        self.x_spinBox_3.setGeometry(QtCore.QRect(50, 60, 42, 22))
        self.x_spinBox_3.setObjectName("x_spinBox_3")
        self.x_spinBox_3.setMaximum(5000)
        self.x_label_2 = QtWidgets.QLabel(self.transformation_groupBox_3)
        self.x_label_2.setGeometry(QtCore.QRect(20, 60, 25, 16))
        self.x_label_2.setObjectName("x_label_2")
        self.y_label_2 = QtWidgets.QLabel(self.transformation_groupBox_3)
        self.y_label_2.setGeometry(QtCore.QRect(20, 90, 25, 16))
        self.y_label_2.setObjectName("y_label_2")
        self.y_spinBox_4 = QtWidgets.QSpinBox(self.transformation_groupBox_3)
        self.y_spinBox_4.setGeometry(QtCore.QRect(50, 90, 42, 16))
        self.y_spinBox_4.setObjectName("y_spinBox_4")
        self.y_spinBox_4.setMaximum(5000)
        self.center_label_3 = QtWidgets.QLabel(self.transformation_groupBox_3)
        self.center_label_3.setGeometry(QtCore.QRect(50, 30, 50, 16))
        self.center_label_3.setObjectName("center_label_3")
        self.z_spinBox_5 = QtWidgets.QSpinBox(self.transformation_groupBox_3)
        self.z_spinBox_5.setGeometry(QtCore.QRect(50, 120, 42, 22))
        self.z_spinBox_5.setObjectName("z_spinBox_5")
        self.z_spinBox_5.setMaximum(5000)
        self.z_label_3 = QtWidgets.QLabel(self.transformation_groupBox_3)
        self.z_label_3.setGeometry(QtCore.QRect(20, 125, 25, 16))
        self.z_label_3.setObjectName("z_label_3")
        self.x_spinBox_4 = QtWidgets.QSpinBox(self.transformation_groupBox_3)
        self.x_spinBox_4.setGeometry(QtCore.QRect(190, 60, 42, 22))
        self.x_spinBox_4.setObjectName("x_spinBox_4")
        self.x_spinBox_4.setMaximum(5000)
        self.x_label_3 = QtWidgets.QLabel(self.transformation_groupBox_3)
        self.x_label_3.setGeometry(QtCore.QRect(120, 60, 61, 16))
        self.x_label_3.setObjectName("x_label_3")
        self.orientation_label_4 = QtWidgets.QLabel(
            self.transformation_groupBox_3)
        self.orientation_label_4.setGeometry(QtCore.QRect(170, 30, 71, 16))
        self.orientation_label_4.setObjectName("orientation_label_4")
        self.x_spinBox_5 = QtWidgets.QSpinBox(self.transformation_groupBox_3)
        self.x_spinBox_5.setGeometry(QtCore.QRect(190, 90, 42, 22))
        self.x_spinBox_5.setObjectName("x_spinBox_5")
        self.x_spinBox_5.setMaximum(5000)
        self.x_label_4 = QtWidgets.QLabel(self.transformation_groupBox_3)
        self.x_label_4.setGeometry(QtCore.QRect(130, 90, 51, 16))
        self.x_label_4.setObjectName("x_label_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raytracer_COSIG"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.scene_groupBox.setTitle(_translate("MainWindow", "Scene"))
        self.load_btn.setText(_translate("MainWindow", "Load"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.camera_groupBox.setTitle(_translate("MainWindow", "Camera"))
        self.distance_label.setText(_translate("MainWindow", "Distance"))
        self.fov_label.setText(_translate("MainWindow", "Field of view"))
        self.transformation_groupBox_3.setTitle(
            _translate("MainWindow", "Transformation"))
        self.x_label_2.setText(_translate("MainWindow", "X"))
        self.y_label_2.setText(_translate("MainWindow", "Y"))
        self.center_label_3.setText(_translate("MainWindow", "Center"))
        self.z_label_3.setText(_translate("MainWindow", "Z"))
        self.x_label_3.setText(_translate("MainWindow", "Horizontal"))
        self.orientation_label_4.setText(
            _translate("MainWindow", "Orientation"))
        self.x_label_4.setText(_translate("MainWindow", "Vertical"))
        self.image_groupBox_3.setTitle(_translate("MainWindow", "Image"))
        self.horizontal_label_5.setText(_translate("MainWindow", "Horizontal"))
        self.resolution_label_4.setText(_translate("MainWindow", "Resolution"))
        self.vertical_label_6.setText(_translate("MainWindow", "Vertical"))
        self.renderer_groupBox_4.setTitle(_translate("MainWindow", "Renderer"))
        self.recursion_label_7.setText(
            _translate("MainWindow", "Recursion Depth"))
        self.start_btn_2.setText(_translate("MainWindow", "Start"))

    def load_image(self):

        try:
            print("Load Button")
            path = QFileDialog.getOpenFileName(self.load_btn, 'Open a file', '',
                                            'Scene Files (*.txt)')
            if path != ('', ''):
                print("File path : " + path[0])
                self.start_btn.show()
                self.save_btn.show()
            image_path = path[0]

            imageContents = app.parser(image_path)

            # Image
            self.horizontal_spinBox_6.setValue(int(imageContents["Images"][0]["Resolution"]["X"]))
            self.vertical_spinBox_7.setValue(int(imageContents["Images"][0]["Resolution"]["Y"]))

            # Camera
            self.fov_spinBox.setValue(int(float(imageContents["Cameras"][0]["FOV"])))
            self.distance_spinBox.setValue(int(float(imageContents["Cameras"][0]["Distance"])))
            #TODO Transformation fill with camera transform values
        except:
            self.error_message("No file selected")

        # Não apagues que ainda pode vir a dar jeito
        #graphicsView = QtWidgets.QGraphicsView(self.image_container)
        #pix = QPixmap()
        #pix.load(str(image_path))
        #item = QtWidgets.QGraphicsPixmapItem(pix)
        #scene = QtWidgets.QGraphicsScene(self.image_container)
        #scene.addItem(item)
        #self.image_container.setScene(scene)
        #self.image_container.show()

    def error_message(self, message):
        """
        Displays error message.
        :param lib_main_window.Ui_MainWindow self: The UI itself
        :param str message: Message to be displayed
        """

        msg = QtWidgets.QMessageBox()
        msg.setWindowIcon(QtGui.QIcon('imgs\\error.png'))
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        msg.setText(message)
        msg.setWindowTitle("Error")
        msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
